"use client";
import {useEffect,useState} from "react";
import {createPortal} from "react-dom";
import Link from "next/link";
import {ArrowRight,ShoppingBag} from "lucide-react";
import type {Product} from "@/lib/types";
const money=(n:number)=>new Intl.NumberFormat("en-BD").format(n);
export default function HomeFeaturedProducts(){
 const[products,setProducts]=useState<Product[]>([]),[target,setTarget]=useState<Element|null>(null);
 useEffect(()=>{setTarget(document.querySelector(".site-shell main"));fetch("/api/products").then(r=>r.json()).then(j=>setProducts((j.products||[]).filter((p:Product)=>p.active!==false&&p.stock>0).slice(0,5))).catch(()=>setProducts([]))},[]);
 if(!target||!products.length)return null;
 return createPortal(<section style={{background:"#fffaf4",padding:"54px 0 64px",borderTop:"1px solid #eadfd4"}}><div className="wrap"><div style={{display:"flex",justifyContent:"space-between",alignItems:"end",gap:16,marginBottom:24}}><div><p style={{margin:"0 0 5px",fontSize:12,letterSpacing:2,color:"#8a5d4c",fontWeight:700}}>CUSTOMER PICKS</p><h2 style={{margin:0,fontFamily:"Georgia,serif",fontSize:"clamp(30px,4vw,44px)",fontWeight:400,color:"#351914"}}>Featured Products</h2><p style={{margin:"7px 0 0",color:"#765f54"}}>Real products currently available at TITHONIA.</p></div><Link href="/shop" style={{display:"flex",alignItems:"center",gap:6,color:"#681511",fontWeight:700,textDecoration:"none",whiteSpace:"nowrap"}}>View All <ArrowRight size={15}/></Link></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:16}}>{products.map(p=><article key={p.id} style={{background:"white",border:"1px solid #eadfd4",borderRadius:14,overflow:"hidden",boxShadow:"0 10px 28px rgba(80,35,20,.07)"}}><Link href="/shop" style={{display:"block",textDecoration:"none",color:"inherit"}}><div style={{aspectRatio:"4/5",background:"#f2e6d8",overflow:"hidden"}}>{p.image?<img src={p.image} alt={p.name} style={{width:"100%",height:"100%",objectFit:"cover",display:"block"}}/>:<div style={{height:"100%",display:"grid",placeItems:"center",padding:20,color:"#8b7468",textAlign:"center"}}>Product image coming soon</div>}</div><div style={{padding:15}}><small style={{color:"#8a5d4c",textTransform:"uppercase",letterSpacing:1}}>{p.category}</small><h3 style={{fontFamily:"Georgia,serif",fontSize:18,margin:"6px 0 10px",minHeight:44}}>{p.name}</h3><div style={{fontSize:20,fontWeight:800,color:"#681511",marginBottom:12}}>৳{money(p.price)}</div><span style={{display:"flex",alignItems:"center",justifyContent:"center",gap:7,background:"#681511",color:"white",padding:"11px 12px",borderRadius:8,fontWeight:700,fontSize:13}}><ShoppingBag size={15}/> SELECT & ORDER</span></div></Link></article>)}</div></div></section>,target);
}
