"use client";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";

const API="https://rcxzpvqtlvbfwwdbwmcw.supabase.co/functions/v1/tithonia-staff";
const box:React.CSSProperties={maxWidth:1120,margin:"34px auto",padding:20,fontFamily:"Arial, sans-serif",color:"#2c1914"};
const card:React.CSSProperties={background:"#fff",border:"1px solid #e5d7c8",borderRadius:14,padding:22,boxShadow:"0 10px 30px rgba(70,30,15,.07)",minWidth:0};
const input:React.CSSProperties={width:"100%",padding:"11px 12px",border:"1px solid #d8c7b7",borderRadius:8,background:"#fffdf9",boxSizing:"border-box"};
const btn:React.CSSProperties={border:0,borderRadius:8,padding:"13px 16px",background:"#5b120f",color:"white",cursor:"pointer",fontWeight:700};
const grid:React.CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:12};
const uploadBox:React.CSSProperties={border:"2px dashed #8f5a4b",borderRadius:12,padding:18,background:"#fff8f2",display:"grid",gap:10};
const sizesList=["S","M","L","XL","2XL","3XL","4XL"];

type Product={id:string;name:string;image_url:string|null;category:string;price:number;stock:number;dealer_price:number|null;dealer_min_qty:number};
type Discount={id:string;code:string;type:"percent"|"fixed";value:number;min_order:number;starts_at:string|null;ends_at:string|null;max_uses:number|null;active:boolean};

export default function StaffPage(){
 const [key,setKey]=useState(""); const [ready,setReady]=useState(false); const [denied,setDenied]=useState(false); const [busy,setBusy]=useState(false); const [msg,setMsg]=useState("");
 const [image,setImage]=useState<File|null>(null); const [preview,setPreview]=useState<string|null>(null); const [replacementImage,setReplacementImage]=useState<File|null>(null); const [replaceProductId,setReplaceProductId]=useState("");
 const [products,setProducts]=useState<Product[]>([]); const [discounts,setDiscounts]=useState<Discount[]>([]); const [selectedSizes,setSelectedSizes]=useState<string[]>([]);
 const productNameRef=useRef<HTMLInputElement|null>(null); const galleryRef=useRef<HTMLInputElement|null>(null); const cameraRef=useRef<HTMLInputElement|null>(null);
 const categories=useMemo(()=>["T-Shirt","Three Piece","Saree","Shoes","Western","Tops","Skirt","Formal","Kurti","Dress","Gown","Co-ord Set","Jeans","Pants","Panjabi","Abaya","Hijab","Bags","Accessories"],[]);
 useEffect(()=>{const q=new URLSearchParams(window.location.search).get("access")||sessionStorage.getItem("tithonia-staff-access")||"";if(q){sessionStorage.setItem("tithonia-staff-access",q);setKey(q)}else setDenied(true)},[]);
 useEffect(()=>{if(key)loadAll(true)},[key]);
 useEffect(()=>{if(!image){setPreview(null);return}const u=URL.createObjectURL(image);setPreview(u);return()=>URL.revokeObjectURL(u)},[image]);
 async function call(body:any){const r=await fetch(API,{method:"POST",headers:{"Content-Type":"application/json","x-staff-key":key},body:JSON.stringify(body)});const j=await r.json().catch(()=>({error:"Unexpected response"}));if(!r.ok)throw new Error(j.error||"Request failed");return j}
 async function loadAll(initial=false){try{const j=await call({action:"list"});const p=j.products||[];setProducts(p);setDiscounts(j.discounts||[]);if(p.length&&!replaceProductId)setReplaceProductId(p[0].id);setReady(true);setDenied(false)}catch(e:any){if(initial)setDenied(true);setReady(false);setMsg(e?.message||"Access denied")}}
 function pickImage(file?:File){if(!file)return;if(file.size>15*1024*1024){setMsg("❌ Picture must be 15 MB or smaller.");return}setImage(file);setMsg("")}
 async function addProduct(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!image)return setMsg("❌ Please choose a product picture first.");setBusy(true);setMsg("Uploading picture and saving product...");const form=e.currentTarget;const f=new FormData(form);f.set("action","add_product");f.set("image",image);f.set("featured",f.get("featured")?"true":"false");f.set("sizes",selectedSizes.join(","));try{const r=await fetch(API,{method:"POST",headers:{"x-staff-key":key},body:f});const j=await r.json();if(!r.ok)throw new Error(j.error||"Upload failed");form.reset();setImage(null);setSelectedSizes([]);if(galleryRef.current)galleryRef.current.value="";if(cameraRef.current)cameraRef.current.value="";await loadAll();setMsg("✅ Product saved with picture. Form cleared — ready for next product.");setTimeout(()=>productNameRef.current?.focus(),100)}catch(e:any){setMsg(`❌ ${e?.message||"Could not add product."}`)}setBusy(false)}
 async function replaceImage(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!replacementImage||!replaceProductId)return setMsg("Choose a product and new picture.");setBusy(true);setMsg("Replacing picture...");const f=new FormData();f.set("action","replace_image");f.set("product_id",replaceProductId);f.set("image",replacementImage);try{const r=await fetch(API,{method:"POST",headers:{"x-staff-key":key},body:f});const j=await r.json();if(!r.ok)throw new Error(j.error||"Replace failed");setReplacementImage(null);setMsg("✅ Product image updated.");await loadAll()}catch(e:any){setMsg(`❌ ${e?.message||"Could not update image."}`)}setBusy(false)}
 async function addDiscount(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const form=e.currentTarget;const f=new FormData(form);const discount={code:String(f.get("code")||""),type:String(f.get("type")||"percent"),value:Number(f.get("value")||0),min_order:Number(f.get("min_order")||0),starts_at:f.get("starts_at")?new Date(String(f.get("starts_at"))).toISOString():null,ends_at:f.get("ends_at")?new Date(String(f.get("ends_at"))).toISOString():null,max_uses:f.get("max_uses")?Number(f.get("max_uses")):null};try{await call({action:"add_discount",discount});form.reset();setMsg("✅ Discount added.");await loadAll()}catch(e:any){setMsg(`❌ ${e?.message||"Could not add discount."}`)}setBusy(false)}
 async function editDiscount(e:FormEvent<HTMLFormElement>,id:string){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);const discount={code:String(f.get("code")||""),type:String(f.get("type")||"percent"),value:Number(f.get("value")||0),min_order:Number(f.get("min_order")||0),starts_at:f.get("starts_at")?new Date(String(f.get("starts_at"))).toISOString():null,ends_at:f.get("ends_at")?new Date(String(f.get("ends_at"))).toISOString():null,max_uses:f.get("max_uses")?Number(f.get("max_uses")):null,active:f.get("active")==="on"};try{await call({action:"update_discount",id,discount});setMsg("✅ Discount updated.");await loadAll()}catch(e:any){setMsg(`❌ ${e?.message||"Could not update discount."}`)}setBusy(false)}
 const dt=(v:string|null)=>v?new Date(v).toISOString().slice(0,16):"";
 if(denied&&!ready)return <main style={box}><div style={{...card,maxWidth:540,margin:"70px auto"}}><h1 style={{fontFamily:"Georgia,serif",fontWeight:400}}>Access denied</h1><p>Use the private TITHONIA staff link.</p></div></main>;
 if(!ready)return <main style={box}><div style={{...card,maxWidth:540,margin:"70px auto"}}><h1 style={{fontFamily:"Georgia,serif",fontWeight:400}}>Opening TITHONIA Staff Panel…</h1></div></main>;
 return <main style={box}>
  <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:20,flexWrap:"wrap"}}><div><h1 style={{fontFamily:"Georgia,serif",fontWeight:400,marginBottom:4}}>TITHONIA Staff Panel</h1><p style={{marginTop:0,color:"#765f54"}}>Direct private-link access.</p></div><button style={{...btn,background:"#765f54"}} onClick={()=>{sessionStorage.removeItem("tithonia-staff-access");window.location.href="/staff"}}>Lock Panel</button></div>
  {msg&&<div style={{...card,marginBottom:16,padding:14,fontWeight:600}}>{msg}</div>}
  <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(300px,1fr))",gap:18}}>
   <section style={card}><h2>Add Product</h2><form onSubmit={addProduct} style={{display:"grid",gap:12}}>
    <input ref={productNameRef} style={input} name="name" placeholder="Product name" required/>
    <div style={grid}><select style={input} name="category" required>{categories.map(c=><option key={c}>{c}</option>)}</select><input style={input} name="sku" placeholder="SKU (optional)"/></div>
    <textarea style={{...input,minHeight:110}} name="description" placeholder="Description" required/>
    <div style={grid}><input style={input} name="price" type="number" min="0" step="0.01" placeholder="Regular price" required/><input style={input} name="compare_at_price" type="number" min="0" step="0.01" placeholder="Old price (optional)"/><input style={input} name="stock" type="number" min="0" placeholder="Stock" required/></div>
    <div style={{...uploadBox,borderStyle:"solid"}}><strong>Dealer / Bulk Price</strong><span style={{fontSize:13,color:"#765f54"}}>Example: minimum 10 pcs, dealer price ৳900 each. Leave dealer price blank if not needed.</span><div style={grid}><input style={input} name="dealer_min_qty" type="number" min="2" max="999" defaultValue="10" placeholder="Minimum qty"/><input style={input} name="dealer_price" type="number" min="0" step="0.01" placeholder="Dealer price per piece"/></div></div>
    <div style={{...uploadBox,borderStyle:"solid"}}><strong>Sizes</strong><div style={{display:"flex",gap:10,flexWrap:"wrap"}}>{sizesList.map(s=><label key={s} style={{border:"1px solid #d8c7b7",borderRadius:8,padding:"8px 10px",background:selectedSizes.includes(s)?"#f2e5da":"#fff"}}><input type="checkbox" checked={selectedSizes.includes(s)} onChange={e=>setSelectedSizes(v=>e.target.checked?[...v,s]:v.filter(x=>x!==s))}/> {s}</label>)}</div></div>
    <input style={input} name="colors" placeholder="Colors: Off White, Maroon"/>
    <div style={uploadBox}><strong style={{fontSize:18,color:"#5b120f"}}>Product Picture *</strong><span style={{fontSize:13,color:"#765f54"}}>Mobile upload fixed: choose Gallery or Camera. JPG/PNG/WEBP/HEIC/AVIF up to 15 MB.</span><div style={grid}><button type="button" style={btn} onClick={()=>galleryRef.current?.click()}>CHOOSE FROM GALLERY</button><button type="button" style={{...btn,background:"#765f54"}} onClick={()=>cameraRef.current?.click()}>TAKE PHOTO</button></div><input ref={galleryRef} type="file" accept="image/*" style={{display:"none"}} onChange={e=>pickImage(e.target.files?.[0])}/><input ref={cameraRef} type="file" accept="image/*" capture="environment" style={{display:"none"}} onChange={e=>pickImage(e.target.files?.[0])}/>{preview&&<div style={{display:"grid",gridTemplateColumns:"120px minmax(0,1fr)",gap:14,alignItems:"center"}}><img src={preview} alt="Product preview" style={{width:120,height:150,objectFit:"cover",objectPosition:"center",borderRadius:10,border:"1px solid #d8c7b7"}}/><div><b>Selected picture</b><p style={{margin:"6px 0",fontSize:12,color:"#765f54"}}>{image?.name}</p></div></div>}</div>
    <label><input type="checkbox" name="featured"/> Featured product</label>
    <button type="submit" style={{...btn,width:"100%",fontSize:16,opacity:(busy||!image)?.6:1}} disabled={busy||!image}>{busy?"SAVING PRODUCT...":"SAVE PRODUCT"}</button>
    <small style={{color:"#765f54",textAlign:"center"}}>Save হলে form clear হয়ে next product add করার জন্য ready হবে.</small>
   </form></section>
   <section style={card}><h2>Change Product Image</h2><form onSubmit={replaceImage} style={{display:"grid",gap:12}}><select style={input} value={replaceProductId} onChange={e=>setReplaceProductId(e.target.value)} required><option value="">Select product</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input style={input} type="file" accept="image/*" onChange={e=>setReplacementImage(e.target.files?.[0]||null)} required/><button type="submit" style={btn} disabled={busy||!products.length}>SAVE NEW IMAGE</button></form></section>
   <section style={card}><h2>Add Discount</h2><form onSubmit={addDiscount} style={{display:"grid",gap:12}}><input style={input} name="code" placeholder="CODE" required/><select style={input} name="type"><option value="percent">Percent</option><option value="fixed">Fixed amount</option></select><input style={input} name="value" type="number" min="0" step="0.01" placeholder="Value" required/><input style={input} name="min_order" type="number" min="0" step="0.01" placeholder="Minimum order" defaultValue="0"/><label>Starts at<input style={input} name="starts_at" type="datetime-local"/></label><label>Ends at<input style={input} name="ends_at" type="datetime-local"/></label><input style={input} name="max_uses" type="number" min="1" placeholder="Maximum uses (optional)"/><button type="submit" style={btn} disabled={busy}>SAVE DISCOUNT</button></form></section>
   <section style={card}><h2>Edit Your Discounts</h2>{discounts.length===0?<p>No editable discounts yet.</p>:<div style={{display:"grid",gap:14}}>{discounts.map(d=><form key={d.id} onSubmit={e=>editDiscount(e,d.id)} style={{border:"1px solid #eadfd4",borderRadius:10,padding:14,display:"grid",gap:10}}><input style={input} name="code" defaultValue={d.code} required/><select style={input} name="type" defaultValue={d.type}><option value="percent">Percent</option><option value="fixed">Fixed amount</option></select><input style={input} name="value" type="number" min="0" step="0.01" defaultValue={d.value} required/><input style={input} name="min_order" type="number" min="0" step="0.01" defaultValue={d.min_order}/><label>Starts at<input style={input} name="starts_at" type="datetime-local" defaultValue={dt(d.starts_at)}/></label><label>Ends at<input style={input} name="ends_at" type="datetime-local" defaultValue={dt(d.ends_at)}/></label><input style={input} name="max_uses" type="number" min="1" defaultValue={d.max_uses??""}/><label><input type="checkbox" name="active" defaultChecked={d.active}/> Active</label><button type="submit" style={btn} disabled={busy}>SAVE DISCOUNT CHANGES</button></form>)}</div>}</section>
  </div>
 </main>
}
